"""
convert_excel.py
Run this script every time you update reports.xlsx to refresh the website data.
Usage:  python convert_excel.py
"""

import openpyxl
import json
import os
import re

EXCEL_FILE = "reports.xlsx"
OUTPUT_JS  = "data.js"

def parse_month_key(date_range: str) -> str:
    """
    Extract a sortable month key from a date range string.
    E.g. '16th - 21th Feb 2026' -> 'Feb 2026'
    """
    months = ["Jan","Feb","Mar","Apr","May","Jun",
              "Jul","Aug","Sep","Oct","Nov","Dec"]
    for m in months:
        match = re.search(rf'\b({m})\s+(\d{{4}})\b', date_range, re.IGNORECASE)
        if match:
            return f"{match.group(1).capitalize()} {match.group(2)}"
    return "Unknown"

def excel_to_json(filepath):
    wb = openpyxl.load_workbook(filepath)
    ws = wb.active
    headers = [cell.value for cell in ws[1]]
    data = []
    for row_cells in ws.iter_rows(min_row=2): # Iterate over cell objects to get hyperlinks
        # Check if the row is empty (all cells are None or empty strings)
        if not any(cell.value is not None and str(cell.value).strip() != '' for cell in row_cells):
            continue

        row_dict = {}
        for i, cell in enumerate(row_cells):
            if i < len(headers) and headers[i]:
                header_name = headers[i]
                value = str(cell.value).strip() if cell.value is not None else ""

                # If the header is "Links" and there's a hyperlink, use the hyperlink target
                if header_name == "Links" and cell.hyperlink and cell.hyperlink.target:
                    row_dict[header_name] = cell.hyperlink.target
                else:
                    row_dict[header_name] = value
        # Attach computed month label
        dr = row_dict.get("Date Range", "")
        row_dict["_month"] = parse_month_key(dr)
        data.append(row_dict)
    return headers, data

def main():
    if not os.path.exists(EXCEL_FILE):
        print(f"ERROR: '{EXCEL_FILE}' not found in current directory.")
        return

    headers, data = excel_to_json(EXCEL_FILE)

    js_content = f"""// AUTO-GENERATED by convert_excel.py — do not edit manually.
// Run 'python convert_excel.py' after updating reports.xlsx

const REPORT_HEADERS = {json.dumps(headers, ensure_ascii=False, indent=2)};

const REPORT_DATA = {json.dumps(data, ensure_ascii=False, indent=2)};
"""
    with open(OUTPUT_JS, "w", encoding="utf-8") as f:
        f.write(js_content)

    print(f"✅ Done! Exported {len(data)} rows to {OUTPUT_JS}")
    months = sorted(set(r["_month"] for r in data))
    print(f"   Months found: {', '.join(months)}")

if __name__ == "__main__":
    main()
